### ISSUE TITLE
Can I use this mod in 1.19.4?

### ISSUE THREAD

**Issue by glowingstone124** [frodare/FlightHud#20]
when i install this mod in 1.19.4, it crashed.

**Comment by a1342** [comment]
https://github.com/a1342/FlightHud/releases/tag/untagged-99173f91f23ed4e83e24

**Comment by glowingstone124** [comment]
> https://github.com/a1342/FlightHud/releases/tag/untagged-99173f91f23ed4e83e24

this release is empty

**Comment by a1342** [comment]
Sorry, I forgot to publish it, now you can get it

**Comment by a1342** [comment]
Sorry, I forgot to publish it, now you can get it
https://github.com/a1342/FlightHud/releases/tag/1.19.4

**Comment by glowingstone124** [comment]
thx!! I'll try it later
