### ISSUE TITLE
version is missing

### ISSUE THREAD

**Issue by end-user** [frodare/FlightHud#6]
mod version does not appear to be being evaluated at build time.  It's causing the mod loader to report: "[main/WARN]: Mod `flighthud` (${version}) does not respect SemVer - comparison support is limited."

**Comment by frodare** [comment]
What version are you using?

**Comment by end-user** [comment]
That's the problem, isn't it?  jk.  I just pulled and loaded Aug 28's release.

**Comment by frodare** [comment]
Yup, I set myself up for that one :)  OK, then you are using the Fabric Version filename: `flighthud-1.17.1-fabric-7.jar`.  I probably goofed somewhere when upgrading to 1.17.

**Comment by end-user** [comment]
resolved
